// APP
export const USER_LOGOUT = 'USER_LOGOUT'

// ALERT
export const SET_ALERT = 'SET_ALERT'
export const RESET_ALERT = 'RESET_ALERT'

// SPINNER
export const SET_SPINNER = 'SET_SPINNER'
export const RESET_SPINNER = 'RESET_SPINNER'

// STATUS
export const STATUSES_READ_REQUEST = 'STATUSES_READ_REQUEST'
export const STATUSES_READ_SUCCESS = 'STATUSES_READ_SUCCESS'
export const STATUSES_READ_FAILURE = 'STATUSES_READ_FAILURE'
export const STATUSES_COMPLETE = 'STATUSES_COMPLETE'
